2020-10-29 09:15:51.385 - [Info] MITM Version: 1.26
2020-10-29 09:15:51.394 - [Info] Auto Access Enabled: true
2020-10-29 09:15:51.394 - [Debug] [Init] Auto Access Barrier: true
2020-10-29 09:15:51.461 - [Info] SSH man-in-the-middle server for 172.20.0.202 listening on 0.0.0.0:10001
2020-10-29 09:16:00.820 - [Debug] [Connection] Attacker connected: 195.3.147.47 | Client Identification: SSH-2.0-Nmap_SSH2_Hostkey  
2020-10-29 09:16:01.963 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "none"
2020-10-29 09:16:01.964 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 09:16:02.232 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "password"
2020-10-29 09:16:02.234 - [Debug] [Auto Access] Attacker: 195.3.147.47, Threshold: 1, Attempts: 1
2020-10-29 09:16:02.234 - [Debug] [Auto Access] Compromising the honeypot
2020-10-29 09:16:02.235 - [Debug] [Auto Access] Adding the following credentials: "ubnt:admin"
2020-10-29 09:16:02.829 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-29 09:16:02.830 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.202
2020-10-29 09:16:06.769 - [Debug] [Connection] Attacker connected: 193.105.134.45 | Client Identification: SSH-2.0-Nmap_SSH2_Hostkey  
2020-10-29 09:16:07.950 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "none"
2020-10-29 09:16:07.951 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 09:16:08.231 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "password"
2020-10-29 09:16:08.232 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-29 09:16:08.233 - [Debug] [Auth] Attacker: 193.105.134.45 has so far made 1 attempts. Remaining: 5 attempts
2020-10-29 09:16:08.521 - [Debug] [Connection] Attacker closed the connection
2020-10-29 09:16:18.208 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-29 09:16:20.033 - [Debug] [Connection] Attacker closed connection
2020-10-29 09:16:20.045 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-29 09:16:20.046 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-29 09:17:03.531 - [Debug] [Connection] Attacker connected: 195.3.147.47 | Client Identification: SSH-2.0-PuTTY_Release_0.61
2020-10-29 09:17:05.088 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "none"
2020-10-29 09:17:05.089 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 09:17:05.349 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "password"
2020-10-29 09:17:05.350 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-29 09:17:05.351 - [Debug] [Auth] Attacker: 195.3.147.47 has so far made 1 attempts. Remaining: 5 attempts
2020-10-29 09:17:05.610 - [Debug] [Connection] Attacker closed the connection
2020-10-29 09:19:33.892 - [Debug] [Connection] Attacker connected: 195.3.147.47 | Client Identification: SSH-2.0-libssh_0.5.5
2020-10-29 09:19:35.541 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "none"
2020-10-29 09:19:35.542 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 09:19:35.812 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "password"
2020-10-29 09:19:35.813 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-29 09:19:35.814 - [Debug] [Auth] Attacker: 195.3.147.47 has so far made 1 attempts. Remaining: 5 attempts
2020-10-29 09:19:36.081 - [Debug] [Connection] Attacker closed the connection
2020-10-29 09:20:21.173 - [Debug] [Connection] Attacker connected: 109.236.91.85 | Client Identification: SSH-2.0-OpenSSH_6.0
2020-10-29 09:20:22.508 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "none"
2020-10-29 09:20:22.508 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 09:20:22.728 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "password"
2020-10-29 09:20:22.729 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2020-10-29 09:20:22.730 - [Debug] [Auth] Attacker: 109.236.91.85 has so far made 1 attempts. Remaining: 5 attempts
2020-10-29 09:20:22.948 - [Debug] [Connection] Attacker closed the connection
