2020-10-28 22:12:09.736 - [Info] MITM Version: 1.26
2020-10-28 22:12:09.748 - [Info] Auto Access Enabled: true
2020-10-28 22:12:09.748 - [Debug] [Init] Auto Access Barrier: true
2020-10-28 22:12:09.787 - [Info] SSH man-in-the-middle server for 172.20.0.202 listening on 0.0.0.0:10001
2020-10-28 22:12:37.084 - [Debug] [Connection] Attacker connected: 195.3.147.47 | Client Identification: SSH-2.0-WinSCP_release_5.7.6
2020-10-28 22:12:38.756 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "none"
2020-10-28 22:12:38.757 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 22:12:39.025 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "password"
2020-10-28 22:12:39.027 - [Debug] [Auto Access] Attacker: 195.3.147.47, Threshold: 1, Attempts: 1
2020-10-28 22:12:39.027 - [Debug] [Auto Access] Compromising the honeypot
2020-10-28 22:12:39.027 - [Debug] [Auto Access] Adding the following credentials: "test:123123"
2020-10-28 22:12:39.659 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-28 22:12:39.659 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.202
2020-10-28 22:12:55.113 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-28 22:12:56.974 - [Debug] [Connection] Attacker closed connection
2020-10-28 22:12:57.011 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-28 22:12:57.012 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-28 22:13:06.586 - [Debug] [Connection] Attacker connected: 109.236.91.85 | Client Identification: SSH-2.0-PuTTY_Snapshot_2010_02_20
2020-10-28 22:13:07.836 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "none"
2020-10-28 22:13:07.836 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 22:13:08.055 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "password"
2020-10-28 22:13:08.056 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-28 22:13:08.057 - [Debug] [Auth] Attacker: 109.236.91.85 has so far made 1 attempts. Remaining: 5 attempts
2020-10-28 22:13:08.276 - [Debug] [Connection] Attacker closed the connection
