2020-10-29 07:57:54.063 - [Info] MITM Version: 1.26
2020-10-29 07:57:54.078 - [Info] Auto Access Enabled: true
2020-10-29 07:57:54.079 - [Debug] [Init] Auto Access Barrier: true
2020-10-29 07:57:54.134 - [Info] SSH man-in-the-middle server for 172.20.0.201 listening on 0.0.0.0:10000
2020-10-29 08:12:29.901 - [Debug] [Connection] Attacker connected: 141.98.81.141 | Client Identification: SSH-2.0-Go
2020-10-29 08:12:31.123 - [Debug] [Auth] Attacker 141.98.81.141 trying to authenticate with "none"
2020-10-29 08:12:31.124 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 08:12:31.475 - [Debug] [Auth] Attacker 141.98.81.141 trying to authenticate with "password"
2020-10-29 08:12:31.477 - [Debug] [Auto Access] Attacker: 141.98.81.141, Threshold: 1, Attempts: 1
2020-10-29 08:12:31.477 - [Debug] [Auto Access] Compromising the honeypot
2020-10-29 08:12:31.478 - [Debug] [Auto Access] Adding the following credentials: "root:root"
2020-10-29 08:12:31.698 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-29 08:12:31.698 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.201
2020-10-29 08:12:31.750 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-29 08:12:33.316 - [Debug] [Connection] Attacker closed connection
2020-10-29 08:12:33.324 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-29 08:12:33.325 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-29 08:15:37.414 - [Debug] [Connection] Attacker connected: 141.98.81.141 | Client Identification: SSH-2.0-Go
2020-10-29 08:15:37.975 - [Debug] [Auth] Attacker 141.98.81.141 trying to authenticate with "none"
2020-10-29 08:15:37.976 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 08:15:38.187 - [Debug] [Auth] Attacker 141.98.81.141 trying to authenticate with "password"
2020-10-29 08:15:38.188 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-29 08:15:38.189 - [Debug] [Auth] Attacker: 141.98.81.141 has so far made 1 attempts. Remaining: 5 attempts
2020-10-29 08:15:38.400 - [Debug] [Connection] Attacker closed the connection
2020-10-29 08:15:52.043 - [Debug] [Connection] Attacker connected: 109.236.91.85 | Client Identification: SSH-2.0-PuTTY_Release_0.66
2020-10-29 08:15:53.078 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "none"
2020-10-29 08:15:53.078 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-29 08:15:53.298 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "password"
2020-10-29 08:15:53.299 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-29 08:15:53.300 - [Debug] [Auth] Attacker: 109.236.91.85 has so far made 1 attempts. Remaining: 5 attempts
2020-10-29 08:15:53.521 - [Debug] [Connection] Attacker closed the connection
